### ISSUE TITLE
Add a bottom to top button

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#40]
Place this button at the bottom-right corner of the screen, easily accessible to users as they scroll down the page. When clicked, the button smoothly and swiftly scrolls the user back to the top, eliminating the need for manual scrolling or repeated mouse wheel actions.

**Comment by sudipkotal** [comment]
Please assign me this task jwoc

**Comment by ritika728** [comment]
@sudipkotal since you are already assigned to issue #33 right now, you can't be assigned to this one.

**Comment by debuuuu007** [comment]
I would like to work in this issue under JWOC'24.

**Comment by Hemant5104** [comment]
I would like to work on that issue under JWOC'24

**Comment by PranavBarthwal** [comment]
I would like to work on this. under jwoc'24

**Comment by ritika728** [comment]
@debuuuu007 assigned

**Comment by debuuuu007** [comment]
Mam i am having some doubts

1. Will every page will have that button including the calculator ones? As calculator pages does not have any work with that button.
2. Do you have any design of the button or i will make a new one of my own?
3. I am thinking that as a person will scroll a little bit like 10-20px the button would be visible otherwise it will not be visible.

**Comment by ritika728** [comment]
> Mam i am having some doubts
> 
> 1. Will every page will have that button including the calculator ones? As calculator pages does not have any work with that button.
> 2. Do you have any design of the button or i will make a new one of my own?
> 3. I am thinking that as a person will scroll a little bit like 10-20px the button would be visible otherwise it will not be visible.

Check the discord group, I have answered this there
